version: "3"
services:
  service_nginx:
    container_name: nginx
    restart: always
    image: nginx:stable
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /e/test/nginx:/etc/nginx/conf.d
    privileged: true
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
